- id: test_hall_upstairs
  alias: 'testing 20171107'
  trigger:
    - platform: state
      entity_id: input_boolean.test
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_upper_wall
        brightness: 0
        transition: 780
    - service: light.turn_on
      data:
        entity_id: light.dinner_table_1
        brightness: 0
        transition: 780
    - delay: '00:13:40'
    - service: light.turn_off
      entity_id: light.dinner_table_1
    - service: light.turn_off
      entity_id: light.hall_upper_wall
    - service: homeassistant.turn_off
      entity_id: input_boolean.test


- id: turn_on_hall_upstairs_wall_in_the_morning
  alias: 'Turn on hall upstairs in the morning'
  trigger:
    platform: time
    at: '05:45'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_upper_wall
        brightness: 164
        transition: 1800

- id: radio_select_p4_sthlm
  alias: 'p4 sthlm selected'
  trigger:
    - platform: state
      entity_id: input_select.radio_select
      to: "P4 Stockholm"
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.kok
        media_content_id: http://opml.radiotime.com/Tune.ashx?id=s47341&partnerId=16
        media_content_type: CHANNEL

- id: radio_select_p4_vstbtn
  alias: 'p4 vstbtn selected'
  trigger:
    - platform: state
      entity_id: input_select.radio_select
      to: "P4 Västerbotten"
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.kok
        media_content_id: http://opml.radiotime.com/Tune.ashx?id=s1295&partnerId=16
        media_content_type: CHANNEL

- id: radio_select_none
  alias: 'radio select none'
  trigger:
    - platform: state
      entity_id: input_select.radio_select
      to: "None"
  action:
    - service: media_player.media_play_pause
      data:
        entity_id: media_player.kok


- id: turn_on_flower_switches
  alias: 'Turn on flower lamps'
  trigger:
    platform: time
    at: '05:30'
  action:
    service: homeassistant.turn_on
    entity_id: 
      - group.livingroom_flowers
      - group.guestroom

- id: turn_off_flower_switches
  alias: 'Turn off flower lamps'
  trigger:
    platform: time
    at: '22:30'
  action:
    service: homeassistant.turn_off
    entity_id: 
      - group.livingroom_flowers
      - group.guestroom


- id: turn_on_kitchen_lamp_in_the_morning
  alias: 'Turn on kitchen lamp in the morning'
  trigger:
    platform: time
    at: '05:45'
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'above_horizon'
  action:
    service: switch.turn_on
    entity_id:
      - switch.kitchen

- id: turn_off_kitchen_lamp_in_the_morning
  trigger:
    platform: time
    at: '08:45'
  action:
    service: switch.turn_off
    entity_id:
      - switch.kitchen

- id: turn_off_bedroom_wall_in_the_morning
  trigger:
    platform: time
    at: '09:00'
  action:
    service: light.turn_off
    entity_id:
      - light.bedroom_wall

- id: turn_off_all_if_not_playing_music_later
  alias: 'Turn off all if not playing music, later...'
  trigger:
    platform: time
    at: '23:30'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.vardagsrumpi
        state: 'paused'
      - condition: state
        entity_id: media_player.vardagsrumpi
        state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.kok
        state: 'paused'
      - condition: state
        entity_id: media_player.kok
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_switches
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime

- id: turn_off_all_if_not_playing
  alias: 'Turn off all if not playing'
  trigger:
    platform: time
    at: '22:30'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.samsung_led46_ue46f5500
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.vardagsrumpi
        state: 'paused'
      - condition: state
        entity_id: media_player.vardagsrumpi
        state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.kok
        state: 'paused'
      - condition: state
        entity_id: media_player.kok
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_switches
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime

- id: light_on_in_the_evening_bedroom
  alias: 'Light on in the evening bedroom'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 7
  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_wall
      brightness: '164'

- id: light_on_in_the_evening_pt3
  alias: 'Light on in the evening 3'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 9
  action:
    service: homeassistant.turn_on
    entity_id: 
      - group.livingroom_switches 

- id: light_on_in_the_evening_pt4
  alias: 'Light on in the evening 4'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 10
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.livingroom_tv_corner
      - group.kitchen


- id: turn_off_sb_when_turning_on_tv
  alias: 'Turn off music when turning on TV'
  trigger:
    platform: state
    entity_id: media_player.samsung_led46_ue46f5500
    to: 'on'
  action:
    service: media_player.media_pause
    entity_id: 
      - media_player.vardagsrumpi
      - media_player.kok


- id: notify_greenhouse_temp_changed
  alias: 'Greenhouse temp'
  trigger:
    - platform: numeric_state
      entity_id: sensor.greenhouse_temperature
      below: 7
      for: '00:10:00'
#    - platform: numeric_state
#      entity_id: sensor.greenhouse_temperature
#      below: 5
    - platform: numeric_state
      entity_id: sensor.greenhouse_temperature
      below: 2
      for: '00:10:00'
    - platform: numeric_state
      entity_id: sensor.greenhouse_temperature
      below: 0
      for: '00:10:00'
    - platform: numeric_state
      entity_id: sensor.greenhouse_temperature
      above: 40
      for: '00:10:00'
  action:
    service: notify.notify_pushbullet
    data:
      title: 'Temp changed'
      message: 'Temperature: {{ states.sensor.greenhouse_temperature.state_with_unit }} Humidity:  {{ states.sensor.greenhouse_humidity.state_with_unit }}'


- id: brightness_dinner_table
  alias: 'Change brightness dinner table'
  trigger:
    - platform: state
      entity_id: input_number.dinner_table_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.dinner_table_1
        brightness: '{{ states.input_number.dinner_table_brightness.state | int }}'
    - service: light.turn_on
      data_template:
        entity_id: light.dinner_table_2
        brightness: '{{ states.input_number.dinner_table_brightness.state | int }}'
    - service: light.turn_on
      data_template:
        entity_id: light.dinner_table_3
        brightness: '{{ states.input_number.dinner_table_brightness.state | int }}'

- id: it_is_bedtime
  alias: 'It is time to go to bed'
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
  action:
    - service: homeassistant.turn_off 
      entity_id: group.night
    - service: light.turn_on
      data:
        entity_id: light.bedroom_wall
        brightness: 0
        transition: 780
    - service: light.turn_on
      data:
        entity_id: light.hall_upper_wall
        brightness: 0
        transition: 780
    - delay: '00:14:00'
    - service: light.turn_off
      entity_id: light.bedroom_wall
    - service: light.turn_off
      entity_id: light.hall_upper_wall
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime

