- platform: yr
  name: 'Weather'

- platform: tellstick
  135: Greenhouse
  183: Bedroom
  231: Other
  only_named: True

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: speedtest
  minute:
    - 26
  monitored_conditions:
    - ping
    - download
    - upload

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/ha.perloof.com/cert.pem | awk '{ print $NF }'"

- platform: cpuspeed
