- platform: yr
  name: 'Weather'

- platform: tellstick
  135: Greenhouse
  only_named: True

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: speedtest
  minute:
    - 26
  monitored_conditions:
    - ping
    - download
    - upload
